version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: game/app.log
    maxBytes: 2097152 # 2 MB in bytes
    backupCount: 1
loggers:
  ble_gateway:
    level: INFO
    handlers: [console, file]
    propagate: no
  root:
    level: INFO
    handlers: [console, file]